export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const FETCHING_PLACES = 'FETCHING_PLACES';
export const FETCHING_PLACES_SUCCESS = 'FETCHING_PLACES_SUCCESS';
export const FETCHING_PLACES_ERROR = 'FETCHING_PLACES_ERROR';

export const FETCHING_PLACE_NAMES = 'FETCHING_PLACE_NAMES';
export const FETCHING_PLACE_NAMES_SUCCESS = 'FETCHING_PLACE_NAMES_SUCCESS';
export const FETCHING_PLACE_NAMES_ERROR = 'FETCHING_PLACE_NAMES_ERROR';

export const FETCHING_PLACES_CATEGORIES = 'FETCHING_PLACES_CATEGORIES';
export const FETCHING_PLACES_CATEGORIES_SUCCESS = 'FETCHING_PLACES_CATEGORIES_SUCCESS';
export const FETCHING_PLACES_CATEGORIES_ERROR = 'FETCHING_PLACES_CATEGORIES_ERROR';

export const FETCHING_PLACE_CATEGORY_NAMES = 'FETCHING_PLACE_CATEGORY_NAMES';
export const FETCHING_PLACE_CATEGORY_NAMES_SUCCESS = 'FETCHING_PLACE_CATEGORY_NAMES_SUCCESS';
export const FETCHING_PLACE_CATEGORY_NAMES_ERROR = 'FETCHING_PLACE_CATEGORY_NAMES_ERROR';

export const FETCHING_PRODUCTS_CATEGORIES = 'FETCHING_PRODUCTS_CATEGORIES';
export const FETCHING_PRODUCTS_CATEGORIES_SUCCESS = 'FETCHING_PRODUCTS_CATEGORIES_SUCCESS';
export const FETCHING_PRODUCTS_CATEGORIES_ERROR = 'FETCHING_PRODUCTS_CATEGORIES_ERROR';

export const FETCHING_BRANDS = 'FETCHING_BRANDS';
export const FETCHING_BRANDS_SUCCESS = 'FETCHING_BRANDS_SUCCESS';
export const FETCHING_BRANDS_ERROR = 'FETCHING_BRANDS_ERROR';

export const FETCHING_BRAND_NAMES = 'FETCHING_BRAND_NAMES';
export const FETCHING_BRAND_NAMES_SUCCESS = 'FETCHING_BRAND_NAMES_SUCCESS';
export const FETCHING_BRAND_NAMES_ERROR = 'FETCHING_BRAND_NAMES_ERROR';

export const FETCHING_PRODUCTS = 'FETCHING_PRODUCTS';
export const FETCHING_PRODUCTS_SUCCESS = 'FETCHING_PRODUCTS_SUCCESS';
export const FETCHING_PRODUCTS_ERROR = 'FETCHING_PRODUCTS_ERROR';

export const FETCHING_PRODUCT_NAMES = 'FETCHING_PRODUCT_NAMES';
export const FETCHING_PRODUCT_NAMES_SUCCESS = 'FETCHING_PRODUCT_NAMES_SUCCESS';
export const FETCHING_PRODUCT_NAMES_ERROR = 'FETCHING_PRODUCT_NAMES_ERROR';

export const FETCHING_PRODUCT_CATEGORY_NAMES = 'FETCHING_PRODUCT_CATEGORY_NAMES';
export const FETCHING_PRODUCT_CATEGORY_NAMES_SUCCESS = 'FETCHING_PRODUCT_CATEGORY_NAMES_SUCCESS';
export const FETCHING_PRODUCT_CATEGORY_NAMES_ERROR = 'FETCHING_PRODUCT_CATEGORY_NAMES_ERROR';

export const FETCHING_SHOPPING_LIST = 'FETCHING_SHOPPING_LIST';
export const FETCHING_SHOPPING_LIST_SUCCESS = 'FETCHING_SHOPPING_LIST_SUCCESS';
export const FETCHING_SHOPPING_LIST_ERROR = 'FETCHING_SHOPPING_LIST_ERROR';

export const SAVING_BRANDS = 'SAVING_BRANDS';
export const SAVING_BRANDS_SUCCESS = 'SAVING_BRANDS_SUCCESS';
export const SAVING_BRANDS_ERROR = 'SAVING_BRANDS_ERROR';

export const SAVING_PLACES = 'SAVING_PLACES';
export const SAVING_PLACES_SUCCESS = 'SAVING_PLACES_SUCCESS';
export const SAVING_PLACES_ERROR = 'SAVING_PLACES_ERROR';

export const SAVING_PLACES_CATEGORIES = 'SAVING_PLACES_CATEGORIES';
export const SAVING_PLACES_CATEGORIES_SUCCESS = 'SAVING_PLACES_CATEGORIES_SUCCESS';
export const SAVING_PLACES_CATEGORIES_ERROR = 'SAVING_PLACES_CATEGORIES_ERROR';

export const SAVING_PRODUCTS = 'SAVING_PRODUCTS';
export const SAVING_PRODUCTS_SUCCESS = 'SAVING_PRODUCTS_SUCCESS';
export const SAVING_PRODUCTS_ERROR = 'SAVING_PRODUCTS_ERROR';

export const SAVING_PRODUCTS_CATEGORIES = 'SAVING_PRODUCTS_CATEGORIES';
export const SAVING_PRODUCTS_CATEGORIES_SUCCESS = 'SAVING_PRODUCTS_CATEGORIES_SUCCESS';
export const SAVING_PRODUCTS_CATEGORIES_ERROR = 'SAVING_PRODUCTS_CATEGORIES_ERROR';

export const SAVING_SHOPPING_LIST = 'SAVING_SHOPPING_LIST';
export const SAVING_SHOPPING_LIST_SUCCESS = 'SAVING_SHOPPING_LIST_SUCCESS';
export const SAVING_SHOPPING_LIST_ERROR = 'SAVING_SHOPPING_LIST_ERROR';

export const DELETING_BRANDS = 'DELETING_BRANDS';
export const DELETING_BRANDS_SUCCESS = 'DELETING_BRANDS_SUCCESS';
export const DELETING_BRANDS_ERROR = 'DELETING_BRANDS_ERROR';

export const DELETING_PLACES = 'DELETING_PLACES';
export const DELETING_PLACES_SUCCESS = 'DELETING_PLACES_SUCCESS';
export const DELETING_PLACES_ERROR = 'DELETING_PLACES_ERROR';

export const DELETING_PLACES_CATEGORIES = 'DELETING_PLACES_CATEGORIES';
export const DELETING_PLACES_CATEGORIES_SUCCESS = 'DELETING_PLACES_CATEGORIES_SUCCESS';
export const DELETING_PLACES_CATEGORIES_ERROR = 'DELETING_PLACES_CATEGORIES_ERROR';

export const DELETING_PRODUCTS = 'DELETING_PRODUCTS';
export const DELETING_PRODUCTS_SUCCESS = 'DELETING_PRODUCTS_SUCCESS';
export const DELETING_PRODUCTS_ERROR = 'DELETING_PRODUCTS_ERROR';

export const DELETING_PRODUCT_CATEGORY = 'DELETING_PRODUCT_CATEGORY';
export const DELETING_PRODUCT_CATEGORY_SUCCESS = 'DELETING_PRODUCT_CATEGORY_SUCCESS';
export const DELETING_PRODUCT_CATEGORY_ERROR = 'DELETING_PRODUCT_CATEGORY_ERROR';

export const DELETING_PLACE_CATEGORY = 'DELETING_PLACE_CATEGORY';
export const DELETING_PLACE_CATEGORY_SUCCESS = 'DELETING_PLACE_CATEGORY_SUCCESS';
export const DELETING_PLACE_CATEGORY_ERROR = 'DELETING_PLACE_CATEGORY_ERROR';

export const DELETING_SHOPPING_LIST = 'DELETING_SHOPPING_LIST';
export const DELETING_SHOPPING_LIST_SUCCESS = 'DELETING_SHOPPING_LIST_SUCCESS';
export const DELETING_SHOPPING_LIST_ERROR = 'DELETING_SHOPPING_LIST_ERROR';

export const UPDATING_BRANDS = 'UPDATING_BRANDS';
export const UPDATING_BRANDS_SUCCESS = 'UPDATING_BRANDS_SUCCESS';
export const UPDATING_BRANDS_ERROR = 'UPDATING_BRANDS_ERROR';

export const UPDATING_PLACES = 'UPDATING_PLACES';
export const UPDATING_PLACES_SUCCESS = 'UPDATING_PLACES_SUCCESS';
export const UPDATING_PLACES_ERROR = 'UPDATING_PLACES_ERROR';

export const UPDATING_PLACES_CATEGORIES = 'UPDATING_PLACES_CATEGORIES';
export const UPDATING_PLACES_CATEGORIES_SUCCESS = 'UPDATING_PLACES_CATEGORIES_SUCCESS';
export const UPDATING_PLACES_CATEGORIES_ERROR = 'UPDATING_PLACES_CATEGORIES_ERROR';

export const UPDATING_PRODUCTS = 'UPDATING_PRODUCTS';
export const UPDATING_PRODUCTS_SUCCESS = 'UPDATING_PRODUCTS_SUCCESS';
export const UPDATING_PRODUCTS_ERROR = 'UPDATING_PRODUCTS_ERROR';

export const UPDATING_PRODUCTS_CATEGORIES = 'UPDATING_PRODUCTS_CATEGORIES';
export const UPDATING_PRODUCTS_CATEGORIES_SUCCESS = 'UPDATING_PRODUCTS_CATEGORIES_SUCCESS';
export const UPDATING_PRODUCTS_CATEGORIES_ERROR = 'UPDATING_PRODUCTS_CATEGORIES_ERROR';

export const TOGGLE_NOTIFICATION = 'TOGGLE_NOTIFICATION';

export const ADDING_TO_SHOPPING_LIST = 'ADDING_TO_SHOPPING_LIST';
export const ADDING_TO_SHOPPING_LIST_SUCCESS = 'ADDING_TO_SHOPPING_LIST_SUCCESS';
export const ADDING_TO_SHOPPING_LIST_ERROR = 'ADDING_TO_SHOPPING_LIST_ERROR';

export const DELETING_FROM_SHOPPING_LIST = 'DELETING_FROM_SHOPPING_LIST';
export const DELETING_FROM_SHOPPING_LIST_SUCCESS = 'DELETING_FROM_SHOPPING_LIST_SUCCESS';
export const DELETING_FROM_SHOPPING_LIST_ERROR = 'DELETING_FROM_SHOPPING_LIST_ERROR';

export const CLEAR_SHOPPING_LIST = 'CLEAR_SHOPPING_LIST';

export const REMOVING_BRAND_FROM_LIST = 'REMOVING_BRAND_FROM_LIST';
export const REMOVING_PLACE_FROM_LIST = 'REMOVING_PLACE_FROM_LIST';
export const REMOVING_PLACE_CATEGORY_FROM_LIST = 'REMOVING_PLACE_CATEGORY_FROM_LIST';

export const CONVERT_TO_PURCHASE = 'CONVERT_TO_PURCHASE';
export const UPDATE_PURCHASE_ITEM = 'UPDATE_PURCHASE_ITEM';
export const REMOVE_ITEM_FROM_PURCHASE = 'REMOVE_ITEM_FROM_PURCHASE';
export const CLEAR_PURCHASE = 'CLEAR_PURCHASE';

export const FETCHING_PURCHASE = 'FETCHING_PURCHASE';
export const FETCHING_PURCHASE_ERROR = 'FETCHING_PURCHASE_ERROR';
export const FETCHING_PURCHASE_SUCCESS = 'FETCHING_PURCHASE_SUCCESS';

export const FETCHING_PURCHASES = 'FETCHING_PURCHASES';
export const FETCHING_PURCHASES_ERROR = 'FETCHING_PURCHASES_ERROR';
export const FETCHING_PURCHASES_SUCCESS = 'FETCHING_PURCHASES_SUCCESS';

export const SAVING_PURCHASE_LIST = 'SAVING_PURCHASE_LIST';
export const SAVING_PURCHASE_LIST_ERROR = 'SAVING_PURCHASE_LIST_ERROR';
export const SAVING_PURCHASE_LIST_SUCCESS = 'SAVING_PURCHASE_LIST_SUCCESS';